spring:
  datasource:
    url: jdbc:mysql://rm-uf6e8i940vetuip7l.mysql.rds.aliyuncs.com:3306/smt?useUnicode=true&characterEncoding=utf-8
    username: tomcat-api
    password: XypMsUIw978H
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
server:
  port: 8881
#  上传的题目图片、音频资源的存储位置
upload:
  fileDir: "/home/smtFile/"
