spring:
  datasource:
    url: jdbc:mysql://rm-8vbd1ewlmgv3713u36o.mysql.zhangbei.rds.aliyuncs.com:3306/smt?useUnicode=true&characterEncoding=utf-8
    username: qxy
    password: Bxyssz724@
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
server:
  port: 8080

upload:
  fileDir: "D:/file/"
